# Generated by Django 4.2.20 on 2025-04-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="otp",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_otp_attempt",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="otp_attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="otp_hash",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
